////////////////////////////////
// Generated by CodeFormatter v1.0
// 2022-08-02, 16:27:33
////////////////////////////////
#if ODIN_INSPECTOR
using Sirenix.OdinInspector;
#endif

using System.Collections.Generic;
using UnityEngine;
namespace PureMVCFramework.Entity
{
	public abstract class HybridSystemBase<T1, T2> : ComponentSystemBase where T1 : Component where T2 : IComponentData 
	{
#if ODIN_INSPECTOR
		[ShowIf("showOdinInfo"), ShowInInspector, ListDrawerSettings(IsReadOnly = true)]
#endif
		private readonly List<T1> Components1 = new List<T1>();
#if ODIN_INSPECTOR
		[ShowIf("showOdinInfo"), ShowInInspector, ListDrawerSettings(IsReadOnly = true)]
#endif
		private readonly List<T2> Components2 = new List<T2>();
		private long hash2;
		protected override void OnCreate()
		{
			base.OnCreate();
			hash2 = Entity.StringToHash(typeof(T2).FullName);
		}
		protected override void OnDestroy()
		{
			Components1.Clear();
			Components2.Clear();
			base.OnDestroy();
		}
		public sealed override void InjectEntity(Entity entity)
		{
			if (entity.gameObject == null)
			{
				if (Entities.Contains(entity))
				{
					var i = Entities.IndexOf(entity);
					Entities.RemoveAt(i);
					Components1.RemoveAt(i);
					Components2.RemoveAt(i);
				}
				return;
			}
			var co = entity.gameObject.GetComponent<T1>();
			IComponentData[] c = new IComponentData[1];
			bool tf = co && entity.components.TryGetValue(hash2, out c[0]);
			if (Entities.Contains(entity))
			{
				if (!tf)
				{
					var i = Entities.IndexOf(entity);
					Entities.RemoveAt(i);
					Components1.RemoveAt(i);
					Components2.RemoveAt(i);
					OnEject(entity, co);
				}
			}
			else if (tf)
			{
				Entities.Add(entity);
				Components1.Add(co);
				Components2.Add((T2)c[0]);
			}
		}
		public sealed override void Update()
		{
			for (int i = 0; i < Entities.Count; ++i)
			{
				OnUpdate(i, Entities[i], Components1[i], Components2[i]);
			}
		}
		protected abstract void OnUpdate(int index, Entity entity, T1 component1, T2 component2);
		protected virtual void OnEject(Entity entity, T1 component) { }
	}
	public abstract class HybridSystemBase<T1, T2, T3> : ComponentSystemBase where T1 : Component where T2 : IComponentData where T3 : IComponentData 
	{
#if ODIN_INSPECTOR
		[ShowIf("showOdinInfo"), ShowInInspector, ListDrawerSettings(IsReadOnly = true)]
#endif
		private readonly List<T1> Components1 = new List<T1>();
#if ODIN_INSPECTOR
		[ShowIf("showOdinInfo"), ShowInInspector, ListDrawerSettings(IsReadOnly = true)]
#endif
		private readonly List<T2> Components2 = new List<T2>();
#if ODIN_INSPECTOR
		[ShowIf("showOdinInfo"), ShowInInspector, ListDrawerSettings(IsReadOnly = true)]
#endif
		private readonly List<T3> Components3 = new List<T3>();
		private long hash2;
		private long hash3;
		protected override void OnCreate()
		{
			base.OnCreate();
			hash2 = Entity.StringToHash(typeof(T2).FullName);
			hash3 = Entity.StringToHash(typeof(T3).FullName);
		}
		protected override void OnDestroy()
		{
			Components1.Clear();
			Components2.Clear();
			Components3.Clear();
			base.OnDestroy();
		}
		public sealed override void InjectEntity(Entity entity)
		{
			if (entity.gameObject == null)
			{
				if (Entities.Contains(entity))
				{
					var i = Entities.IndexOf(entity);
					Entities.RemoveAt(i);
					Components1.RemoveAt(i);
					Components2.RemoveAt(i);
					Components3.RemoveAt(i);
				}
				return;
			}
			var co = entity.gameObject.GetComponent<T1>();
			IComponentData[] c = new IComponentData[2];
			bool tf = co && entity.components.TryGetValue(hash2, out c[0]) && entity.components.TryGetValue(hash3, out c[1]);
			if (Entities.Contains(entity))
			{
				if (!tf)
				{
					var i = Entities.IndexOf(entity);
					Entities.RemoveAt(i);
					Components1.RemoveAt(i);
					Components2.RemoveAt(i);
					Components3.RemoveAt(i);
					OnEject(entity, co);
				}
			}
			else if (tf)
			{
				Entities.Add(entity);
				Components1.Add(co);
				Components2.Add((T2)c[0]);
				Components3.Add((T3)c[1]);
			}
		}
		public sealed override void Update()
		{
			for (int i = 0; i < Entities.Count; ++i)
			{
				OnUpdate(i, Entities[i], Components1[i], Components2[i], Components3[i]);
			}
		}
		protected abstract void OnUpdate(int index, Entity entity, T1 component1, T2 component2, T3 component3);
		protected virtual void OnEject(Entity entity, T1 component) { }
	}
	public abstract class HybridSystemBase<T1, T2, T3, T4> : ComponentSystemBase where T1 : Component where T2 : IComponentData where T3 : IComponentData where T4 : IComponentData 
	{
#if ODIN_INSPECTOR
		[ShowIf("showOdinInfo"), ShowInInspector, ListDrawerSettings(IsReadOnly = true)]
#endif
		private readonly List<T1> Components1 = new List<T1>();
#if ODIN_INSPECTOR
		[ShowIf("showOdinInfo"), ShowInInspector, ListDrawerSettings(IsReadOnly = true)]
#endif
		private readonly List<T2> Components2 = new List<T2>();
#if ODIN_INSPECTOR
		[ShowIf("showOdinInfo"), ShowInInspector, ListDrawerSettings(IsReadOnly = true)]
#endif
		private readonly List<T3> Components3 = new List<T3>();
#if ODIN_INSPECTOR
		[ShowIf("showOdinInfo"), ShowInInspector, ListDrawerSettings(IsReadOnly = true)]
#endif
		private readonly List<T4> Components4 = new List<T4>();
		private long hash2;
		private long hash3;
		private long hash4;
		protected override void OnCreate()
		{
			base.OnCreate();
			hash2 = Entity.StringToHash(typeof(T2).FullName);
			hash3 = Entity.StringToHash(typeof(T3).FullName);
			hash4 = Entity.StringToHash(typeof(T4).FullName);
		}
		protected override void OnDestroy()
		{
			Components1.Clear();
			Components2.Clear();
			Components3.Clear();
			Components4.Clear();
			base.OnDestroy();
		}
		public sealed override void InjectEntity(Entity entity)
		{
			if (entity.gameObject == null)
			{
				if (Entities.Contains(entity))
				{
					var i = Entities.IndexOf(entity);
					Entities.RemoveAt(i);
					Components1.RemoveAt(i);
					Components2.RemoveAt(i);
					Components3.RemoveAt(i);
					Components4.RemoveAt(i);
				}
				return;
			}
			var co = entity.gameObject.GetComponent<T1>();
			IComponentData[] c = new IComponentData[3];
			bool tf = co && entity.components.TryGetValue(hash2, out c[0]) && entity.components.TryGetValue(hash3, out c[1]) && entity.components.TryGetValue(hash4, out c[2]);
			if (Entities.Contains(entity))
			{
				if (!tf)
				{
					var i = Entities.IndexOf(entity);
					Entities.RemoveAt(i);
					Components1.RemoveAt(i);
					Components2.RemoveAt(i);
					Components3.RemoveAt(i);
					Components4.RemoveAt(i);
					OnEject(entity, co);
				}
			}
			else if (tf)
			{
				Entities.Add(entity);
				Components1.Add(co);
				Components2.Add((T2)c[0]);
				Components3.Add((T3)c[1]);
				Components4.Add((T4)c[2]);
			}
		}
		public sealed override void Update()
		{
			for (int i = 0; i < Entities.Count; ++i)
			{
				OnUpdate(i, Entities[i], Components1[i], Components2[i], Components3[i], Components4[i]);
			}
		}
		protected abstract void OnUpdate(int index, Entity entity, T1 component1, T2 component2, T3 component3, T4 component4);
		protected virtual void OnEject(Entity entity, T1 component) { }
	}
}
